export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_CLASSES = "GET_CLASSES";

export const GET_FORUM_THREADS = "GET_FORUM_THREADS";
export const GET_THREAD = "GET_THREAD";
export const THREADS_LOADING = "THREADS_LOADING";
export const THREAD_LOADING = "THREAD_LOADING";

export const CREATE_NEW_THREAD = "CREATE_THREAD";
export const EDIT_THREAD = "EDIT_THREAD";
export const CREATE_NEW_REPLY = "CREATE_NEW_REPLY";
export const EDIT_REPLY = "EDIT_REPLY";
export const LIKE_THREAD = "LIKE_THREAD";
export const LIKE_REPLY = "LIKE_REPLY";
export const DELETE_THREAD = "DELETE_THREAD";
export const DELETE_REPLY = "DELETE_REPLY";

export const GET_WALLET = "GET_WALLET";
export const SET_WALLET_LOADING = "SET_WALLET_LOADING";

export const GET_INVENTORY = "GET_INVENTORY";
export const SET_INVENTORY_LOADING = "SET_INVENTORY_LOADING";
export const EQUIP_ITEM = "EQUIP_ITEM";
